### ISSUE TITLE
space=0 gives error message

### ISSUE THREAD

**Issue by schonlau** [TianchengY/hammock_plot#2]
space=0 gives error message but didn't use to. 

ax = hammock.plot(var=var, bar_width=1, default_color="lightblue", space=0 , shape="parallelogram") 
ZeroDivisionError: float division by zero

**Comment by schonlau** [comment]
However, space=0 works for the shakespeare data : 

hammock = hammock_plot.Hammock(data_df = data_df)
ax = hammock.plot(var=var,shape="rectangle",label=False, bar_width=2,default_color="lightblue", space=0)

**Comment by TianchengY** [comment]
# maybe to check space and label together
